import { Seller } from "@/lib/types";

export const dummySellers: Seller[] = [
  {
    id: "2323",
    name: "John",
    email: "john@test.com",
    password: "uni123",
    lastName: "Spancy",
    license: "Seller",
    address: "New York",
    profileImg: "src/images/profile01.jpg",
    reviews: [], 
    contacts: ["2323"], 
    notifications: [], 
    products: [], 
    contactRequests: [],
  },
  {
    id: "5454",
    name: "Julio",
    email: "julio@test.com",
    password: "uni123",
    lastName: "Cesar",
    license: "Seller",
    address: "Roman Street, Rome, Italy",
    profileImg: "src/images/profile02.jpg",
    reviews: [],
    contacts: ["5454"],
    notifications: [],
    products: [],
    contactRequests: [],
  },
  {
    id: "7878",
    name: "Juana",
    email: "juana@test.com",
    password: "uni123",
    lastName: "Perez",
    license: "Seller",
    address: "Armenia Quindio",
    profileImg: "src/images/profile03.jpg",
    reviews: [],
    contacts: ["7878"],
    notifications: [],
    products: [],
    contactRequests: [],
  },

];